import type { Metadata } from 'next'
import './globals.css'

import { ApolloClientProvider } from '@/components/apollo-provider'
import { SessionProvider } from '@/components/session-provider'
import { getUserAndSession } from '@/lib/supabase/session'

export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}

export default async function RootLayout({
	children,
}: {
	children: React.ReactNode
}) {
	const { user, session } = await getUserAndSession() // fetch session server-side

	return (
		<html lang="en" data-theme="mytheme-light">
			<body className="bg-neutral text-neutral-content flex items-center justify-center min-h-screen">
				<SessionProvider user={user} session={session}>
					<ApolloClientProvider>{children}</ApolloClientProvider>
				</SessionProvider>
			</body>
		</html>
	)
}
